### ISSUE TITLE
demo安装上刚打开就崩溃了

### ISSUE THREAD

**Issue by yundequanshi** [pqpo/SmartCropper#1]
应该是缺少so文件吧，我看着只有armeabi的so文件

**Comment by yundequanshi** [comment]
华为手机 麦芒3

**Comment by pqpo** [comment]
其他的so我没编译,晚点我编译一些。我看了一些麦芒3是高通的arm处理器，应该支持的呀？报错就是找不到so？

**Comment by MinchinWang** [comment]
我的也报错，华为 Nova 2

**Comment by pqpo** [comment]
能贴一下报错信息不

**Comment by yuger** [comment]
Unable to instantiate activity ComponentInfo{me.pqpo.smartcropper/me.pqpo.smartcropper.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "me.pqpo.smartcropper.MainActivity" on path: DexPathList[[zip file "/data/app/me.pqpo.smartcropper-1/base.apk"],nativeLibraryDirectories=[/data/app/me.pqpo.smartcropper-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by pqpo** [comment]
不好意思，包传错了，已经更新。
