### ISSUE TITLE
这个native层只要crop后内存能开辟三四百M

### ISSUE THREAD

**Issue by Mangosir** [pqpo/SmartCropper#100]
native层只要scan/crop后，内存能开辟三四百M，而且一直释放不了，作者有什么优化吗

**Comment by pqpo** [comment]
主要是 HED 网络识别时需要申请大量内存，位置在 native 上：
private int desiredSize = 256;
imgData = ByteBuffer.allocateDirect(desiredSize * desiredSize * 3 * Float.SIZE / Byte.SIZE);
outImgData = ByteBuffer.allocateDirect(desiredSize * desiredSize * Float.SIZE / Byte.SIZE);

**Comment by bikerr** [comment]
> 主要是 HED 网络识别时需要申请大量内存，位置在 native 上：
> private int desiredSize = 256;
> imgData = ByteBuffer.allocateDirect(desiredSize * desiredSize * 3 * Float.SIZE / Byte.SIZE);
> outImgData = ByteBuffer.allocateDirect(desiredSize * desiredSize * Float.SIZE / Byte.SIZE);

按照这个大小计算 这两块申请的内存也只有不到2M而已 ，应该不是这个导致内存开辟300-400M的吧

**Comment by pqpo** [comment]
TensorFlow lite Interpreter 持有的内存，使用之后调用 Interpreter.close 即可释放内存，之后会开个 release 方法出来，在页面退出不再使用推理模型时调用。

**Comment by star-heng** [comment]
这个升级org.tensorflow:tensorflow-lite问题就没有了
