### ISSUE TITLE
CMakeList.txt使用target_link_libraries替换find_library，否则NDK版本高于19就会报错error: undefined reference to '__write_chk'

### ISSUE THREAD

**Issue by jiyewushen** [pqpo/SmartCropper#106]
[NDK issue](https://github.com/android/ndk/issues/1179)
建议：直接使用target_link_libraries替换find_library
```CMake
# find_library(log-lib log)
# find_library(jnigraphics-lib jnigraphics)
# find_library(z-lib z)
target_link_libraries(log jnigraphics z)
```

**Comment by pqpo** [comment]
done

**Comment by gitgeek4dx** [comment]
good, it works

**Comment by gitgeek4dx** [comment]
and need to delete libz in below target_lin_libraries code:

if(${ANDROID_ABI} STREQUAL x86 OR ${ANDROID_ABI} STREQUAL x86_64)
target_link_libraries(${TARGET} opencv_imgproc opencv_core ippiw ippicv ittnotify tbb cpufeatures)
else()
target_link_libraries(${TARGET} opencv_imgproc opencv_core tegra_hal tbb cpufeatures)
endif()
