### ISSUE TITLE
Build failed. (smartcropperlib/.externalNativeBuild/cmake/debug/arm64-v8a --target smart_cropper})

### ISSUE THREAD

**Issue by lokeshdesai403** [pqpo/SmartCropper#107]
Build command failed.
Error while executing process /Users/lokesh/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/lokesh/Projects/Android/MyProjects/CentricwaveScannerApp/gitcode/hapscan_android/HapScan/smartcropperlib/.externalNativeBuild/cmake/debug/arm64-v8a --target smart_cropper}
[1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
[2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
[3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
[4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libsmart_cropper.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libsmart_cropper.so 
: && /Users/lokesh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/Users/lokesh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/lokesh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libsmart_cropper.so -o ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libsmart_cropper.so CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o -L/Users/lokesh/Projects/Android/MyProjects/CentricwaveScannerApp/gitcode/hapscan_android/HapScan/smartcropperlib/../opencv410/native/lib/arm64-v8a  -L/Users/lokesh/Projects/Android/MyProjects/CentricwaveScannerApp/gitcode/hapscan_android/HapScan/smartcropperlib/../opencv410/native/3rdparty/libs/arm64-v8a -llog -ljnigraphics -lz -lopencv_imgproc -lopencv_core -ltegra_hal -ltbb -lcpufeatures -latomic -lm && :
/Users/lokesh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lopencv_imgproc
/Users/lokesh/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lopencv_core
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by nxnyk** [comment]
你好，请问怎么解决的？
