### ISSUE TITLE
编译smartcropperlib报错

### ISSUE THREAD

**Issue by httplzc** [pqpo/SmartCropper#11]
错误如下：
Warning:warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
Warning:warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
Warning:warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
Error:error: undefined reference to 'tbb::task_scheduler_init::terminate()'
Error:error: undefined reference to 'tbb::task_scheduler_init::initialize(int, unsigned int)'
Error:error: linker command failed with exit code 1 (use -v to see invocation)

请问该怎么解决？

**Comment by weichao66666** [comment]
我遇到了一样的问题
想编译 'armeabi', 'armeabi-v7a', 'arm64-v8a','x86', 'x86_64', 'mips', 'mips64'
发现只有 'armeabi' 没问题
'arm64-v8a', 'x86_64'', 'mips64' 在 lib 中没有 也不知道 OpenCV-android-sdk 用的是哪个版本的？换版本会报错
lib 中有的 'armeabi-v7a','x86', 'mips' 都报这个错 没查到怎么解决？ 也不知道问题出在哪？ 
回家再试试 Linux 环境下编译吧

**Comment by httplzc** [comment]
其实是缺少了tbb这个东西。可以去openCv官网下载完整包，里面3rdparty文件夹中的libtbb.a文件放入项目opencv  目录下的lib中。并且在cMakeList中引用即可正常编译
