### ISSUE TITLE
Borders not identified

### ISSUE THREAD

**Issue by rahulas** [pqpo/SmartCropper#12]
Hi, Thanks for the great library.  I've download and ran the demo app and could successfully run the app the get the expected result without any crashes. But as you mentioned in the Readme file, borders are not identified for a document or business card in the image. Can you please fix this in code? It would a great help if you fix this in next release.

**Comment by pqpo** [comment]
Hi, Thanks for using. The current algorithm actually cannot works well in all situations  which the borders of image is not clear. Maybe using deep learning is a better way and I will work for it. Is it convenient to provide the image that not identified?
