### ISSUE TITLE
选点怎么选不对啊....

### ISSUE THREAD

**Issue by FangforFun** [pqpo/SmartCropper#16]

**Comment by pqpo** [comment]
具体是怎么选不对，能否提供更多信息

**Comment by FangforFun** [comment]
![qq 20171202120846](https://user-images.githubusercontent.com/23162290/33511661-b7762920-d759-11e7-9058-903b85e08b7c.jpg)
默认选点

**Comment by pqpo** [comment]
https://github.com/pqpo/SmartCropper/issues/8
https://github.com/pqpo/SmartCropper/issues/12
