### ISSUE TITLE
怎么旋转图片？

### ISSUE THREAD

**Issue by TopTime1** [pqpo/SmartCropper#17]
比如说横屏拍照，照片竖着，截出来也是竖屏，但是我需要横屏显示，这个怎么解决下呢？

**Comment by pqpo** [comment]
你指的是横屏拍一张竖着的名片？ 系统能判断的是拍照的方向，并不能识别你拍摄的物体是横着还是竖着的，最终还是要根据业务场景来判断是否旋转，比如根据截图的长宽。截图的结果是可以拿到 Bitmap 的，旋转之后再显示便是了。至于如何旋转 Bitmap，google 一下即可。

**Comment by TopTime1** [comment]
好的多谢
