### ISSUE TITLE
可以固定四个角不向相反的方向拉吗

### ISSUE THREAD

**Issue by TopTime1** [pqpo/SmartCropper#21]
可以固定四个角不向相反的方向拉吗？，图片会出现反的问题 
![Uploading image.png…]()

**Comment by pqpo** [comment]
图片挂了，相反方向是指？裁剪的时候做了凸四边形校验

**Comment by TopTime1** [comment]
![image](https://user-images.githubusercontent.com/7701170/35264860-45dbde62-0059-11e8-8a28-27820ec8c3b0.png)

图片是这样的

**Comment by pqpo** [comment]
已经改了，试试新版本，再次感谢你的建议

**Comment by TopTime1** [comment]
compile 'com.github.pqpo:SmartCropper:v1.1.0@aar'，是这个版本吗？

**Comment by pqpo** [comment]
v1.1.1

**Comment by apsense** [comment]
你编译的版本号没有修改为1.1.1， 还是老的1.1.0

**Comment by TopTime1** [comment]
compile 'com.github.pqpo:SmartCropper:v1.1.1@aar'，
![image](https://user-images.githubusercontent.com/7701170/35322980-0ace399a-0127-11e8-810c-f9282a190129.png)
1.1.2吧

**Comment by pqpo** [comment]
抱歉，刚刚版本弄混了，试试 v1.1.2 看看

**Comment by TopTime1** [comment]
![image](https://user-images.githubusercontent.com/7701170/35323974-4c0c5b3c-012a-11e8-94f9-f747147d37fa.png)有bug，点一重叠就乱了

**Comment by TopTime1** [comment]
请问这个能解决吗

**Comment by pqpo** [comment]
在解决了，试了几种方案，都有点问题

**Comment by TopTime1** [comment]
好的，麻烦了大神，解决了希望给个回复，多谢！我这边先用1.1.0的版本

**Comment by pqpo** [comment]
感觉被你带入误区了：），用户只要依次拖动锚点旋转之后就能截取左右对称的图，这样的话就没好办法了

**Comment by TopTime1** [comment]
因为有的时候识别不出边缘位置来，四个点会重叠在一起，用户就分不清左上,右上,左下,右下四个点，所以很有可能会拉反，就会造成我上边的截图那样。我qq981855057

**Comment by pqpo** [comment]
这种情况业务层是否可以做个判断，如果识别出的四个点距离太近就给个默认值或者直接调用
 setFullImgCrop 全屏

**Comment by TopTime1** [comment]
但是这样还是不能解决用户非得反着拉四个点的问题，设置默认值有提供方法吗？

**Comment by pqpo** [comment]
发布了 v1.1.3 可以试试，新增了拖动锚点限制为凸四边形。自己设置锚点可以使用 setCropPoints(Point[] cropPoints)，按顺序已图片大小为参考传入四个点坐标。

**Comment by TopTime1** [comment]
好的我这边测试下

**Comment by TopTime1** [comment]
![image](https://user-images.githubusercontent.com/7701170/35435362-61648e36-02c5-11e8-83f3-f51ddc86c549.png)
三角形的时候截出来的也是四边形，还有就是如果我旋转四个点，还是会出现上面那种问题
![image](https://user-images.githubusercontent.com/7701170/35435566-2c490e10-02c6-11e8-979d-8ffd734bbc75.png)

**Comment by TopTime1** [comment]
请问还有解决方案吗？

**Comment by pqpo** [comment]
暂时没有，不然就是要加跟多限制，何况用户自己要拖成这样也没办法

**Comment by TopTime1** [comment]
好的，你这边能不能比如说没有识别出来边缘的四个点，然后设置个默认的，这样至少点不会重叠在一起？

**Comment by pqpo** [comment]
默认值你可以自己设置啊
