### ISSUE TITLE
能不能增加一些裁剪之后的图像增强的功能方便使用

### ISSUE THREAD

**Issue by zengqingsong** [pqpo/SmartCropper#22]
希望能够增加：增加亮度、锐化、转换为灰度等基本的图像增强功能，因为扫描得到的文稿除了需要裁剪，有时候不清晰或者偏暗、反光等需要基本的处理，虽然OepnCV中能够实现，但是不熟悉，希望能够继承到这个包中。

**Comment by pqpo** [comment]
后续会考虑增加
