### ISSUE TITLE
拍照后的点没有在四周

### ISSUE THREAD

**Issue by zhangzzqq** [pqpo/SmartCropper#24]
拍一张纸，四个点没有在纸的四周，而是没有规则的显示在上面，需要手动的把它们拉倒四周，请问这个怎样去优化？

**Comment by pqpo** [comment]
拍摄物体与背景反差比较大情况下识别效果会比较好

**Comment by zhangzzqq** [comment]
你看看这个demo  https://github.com/jhansireddy，这个定位文件的效果要好一些

**Comment by pqpo** [comment]
用他的算法试了一下感觉差不多，有些场景我的能识别，他的识别不了。
