### ISSUE TITLE
Please add support for 64-bit abi

### ISSUE THREAD

**Issue by monowar1993** [pqpo/SmartCropper#25]
Please add support for 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'mips64' all this abi's supported by android. or tell me way how I can add them.

**Comment by pqpo** [comment]
The last version v1.1.3 is supported for 'armeabi', 'armabi-v7a', 'x86' and 'mips'. And can support most Android devices.

**Comment by pqpo** [comment]
And 64-bit abi support I will add at next version.
