### ISSUE TITLE
android7.0 不兼容

### ISSUE THREAD

**Issue by yyy000112** [pqpo/SmartCropper#26]
我试了下android7.0 不兼容

**Comment by pqpo** [comment]
麻烦报错贴一下

**Comment by pqpo** [comment]
https://github.com/pqpo/SmartCropper/issues/28
https://github.com/pqpo/SmartCropper/issues/28
Android 7.0 稍后适配

**Comment by yyy000112** [comment]
恩恩，我把你的so文件加进去，然后把ndk {
            abiFilters 'armeabi','armeabi-v7a','mips', 'x86'
        }这个也添加进去了，，但是在photFile.exist()显示false，photFile的路径都能打印出来不为空

**Comment by yyy000112** [comment]
等你弄好，明天要交差-，-

**Comment by pqpo** [comment]
跑 Demo 报错还是集成到其他项目报错？ Android 7.0 需要使用 FileProvider 共享文件，库本身不需要修改，回头我也是改一下 demo。

**Comment by yyy000112** [comment]
集成到项目中，这些FileProvider 都添加了，你改好demo看看，那个photofile.exist()返回变成false了

**Comment by yyy000112** [comment]
还有一个问题就是在7.0中，裁剪没有效果，还是加载了原图
