### ISSUE TITLE
 java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by Brodong** [pqpo/SmartCropper#29]
出现了这个错误是为什么？

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':smartcropperlib'.
      > java.lang.NullPointerException (no error message)

**Comment by pqpo** [comment]
clone 下来之后跑 demo 出现的？
