### ISSUE TITLE
能对识别图片中的边框的算法说明一下吗

### ISSUE THREAD

**Issue by JakeWoki** [pqpo/SmartCropper#3]

**Comment by pqpo** [comment]
边框识别是基于 opencv 的，主要看 vector<Point> Scanner::scanPoint() 方法，将输入的图片缩小到特定大小，做灰化处理，然后小幅度高斯模糊去除噪点，再使用 Canny 算符做边缘检测，接着二值化处理，之后使用 findContours 提取轮廓，最后按面积偏序，多变形逼近，合并距离较近的点。这样说来可能有点抽象，我再添加点注释，直接看代码会形象一点。

**Comment by liangtongzhuo** [comment]
good
