### ISSUE TITLE
希望能提供隐藏 裁剪框 的接口

### ISSUE THREAD

**Issue by Likeyong** [pqpo/SmartCropper#32]
原本想通过 cropImageView.setCropPoints(null); 来取消裁剪框对的，但是代码里面进行判定了如果 传入的为null，就会截取整个图片。  我想自己控制裁剪框的出现机制，随时设置裁剪框的可见性。谢谢了

**Comment by Likeyong** [comment]
临时通过  设置 四个选择点 的坐标 全部为 负值  ，然后调整mask透明度，伪实现了 隐藏裁剪框

**Comment by pqpo** [comment]
可以暂时先这样实现一下，后续会考虑添加方法

**Comment by Likeyong** [comment]
谢谢您了
