### ISSUE TITLE
1.1.3 限制凸四边形

### ISSUE THREAD

**Issue by Likeyong** [pqpo/SmartCropper#33]
在1.1.3版本里面限制了凸四边形。图片存在自动识别出的 四边形是凹的情况下，突出的点将不能被拖拽，除非其他点被拖拽了

**Comment by Likeyong** [comment]
如果 凹进去的点 不被拖拽出来，其他点都无法进行拖拽

**Comment by pqpo** [comment]
可以把这个限制去掉：setDragLimit(false)

**Comment by Likeyong** [comment]
非常感谢
