### ISSUE TITLE
关于智能识别身份证正反面自动拍照。

### ISSUE THREAD

**Issue by KomoriWu** [pqpo/SmartCropper#35]
作者有什么好的思路吗。谢谢

**Comment by pqpo** [comment]
OpenCV 有提供目标识别的功能，需要训练一个身份证上国徽的样本。

**Comment by KomoriWu** [comment]
@pqpo  作者你好，我很早就去翻了一遍你的博客。很遗憾没有这方面的帖子，以你对opencv的理解，我感觉你可以很快的写一篇类似的文章出来，造福下我们哈哈。这方面的帖子太少了。谢谢

**Comment by pqpo** [comment]
前几天开源了另一个项目 SmartCamera 你可以看看，大致实现了你的需求，但是不能特定的识别是否是身份证正反面，这个需要大量的训练样本。

**Comment by KomoriWu** [comment]
感谢作者的回复 我去看下
