### ISSUE TITLE
build fail:CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

### ISSUE THREAD

**Issue by Chan2U** [pqpo/SmartCropper#37]
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

**Comment by Zhangoo** [comment]
please refer to
https://stackoverflow.com/questions/50757141/cmake-error-cmake-c-compiler-not-set-after-enablelanguage

**Comment by Chan2U** [comment]
not work for me

**Comment by pqpo** [comment]
Can be solved by downgrading the NDK's version.
