### ISSUE TITLE
可以提供一下编译的NDK版本信息以及opencv的相关数据吗

### ISSUE THREAD

**Issue by leo-wxy** [pqpo/SmartCropper#4]
想要自己去编译一下 .so文件

**Comment by pqpo** [comment]
opencv 静态库与头文件位于 smartcropperlib/opencv 目录下，目前只包含了 armeabi 架构的静态库，其他的可以去官网下载到 http://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html
代码 clone 下去可以直接编译出动态链接库。CMake，NDK 工具使用最新的即可。
如编译出现问题可以继续留言。

**Comment by leo-wxy** [comment]
好的 ，谢谢
