### ISSUE TITLE
demo编译出错了

### ISSUE THREAD

**Issue by jamlu614** [pqpo/SmartCropper#42]
Build command failed.
Error while executing process D:\AndroidSDK\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\android_pro\internet\SmartCropper-master\smartcropperlib\.externalNativeBuild\cmake\debug\armeabi-v7a --target smart_cropper}
[1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
[2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
[3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
FAILED: D:\AndroidSDK\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/AndroidSDK/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/AndroidSDK/sdk/ndk-bundle/sysroot  -Dsmart_cropper_EXPORTS -I../../../../opencv/include -I../../../../src/main/cpp/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/android/support/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -frtti -fexceptions -lz -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o -MF CMakeFiles\smart_cropper.dir\src\main\cpp\smart_cropper.cpp.o.d -o CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o -c D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\smart_cropper.cpp
clang++.exe: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
In file included from D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\smart_cropper.cpp:6:
In file included from ../../../../src/main/cpp/include\android_utils.h:9:
In file included from ../../../../opencv/include\opencv2/opencv.hpp:47:
In file included from ../../../../opencv/include\opencv2/core/core.hpp:4883:
../../../../opencv/include\opencv2/core/operations.hpp:74:16: fatal error: 'ext/atomicity.h' file not found
      #include <ext/atomicity.h>
               ^~~~~~~~~~~~~~~~~
1 error generated.
FAILED: D:\AndroidSDK\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/AndroidSDK/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/AndroidSDK/sdk/ndk-bundle/sysroot  -Dsmart_cropper_EXPORTS -I../../../../opencv/include -I../../../../src/main/cpp/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/android/support/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -frtti -fexceptions -lz -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o -MF CMakeFiles\smart_cropper.dir\src\main\cpp\android_utils.cpp.o.d -o CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o -c D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\android_utils.cpp
clang++.exe: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
In file included from D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\android_utils.cpp:4:
In file included from ../../../../src/main/cpp/include\android_utils.h:9:
In file included from ../../../../opencv/include\opencv2/opencv.hpp:47:
In file included from ../../../../opencv/include\opencv2/core/core.hpp:4883:
../../../../opencv/include\opencv2/core/operations.hpp:74:16: fatal error: 'ext/atomicity.h' file not found
      #include <ext/atomicity.h>
               ^~~~~~~~~~~~~~~~~
1 error generated.
FAILED: D:\AndroidSDK\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/AndroidSDK/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/AndroidSDK/sdk/ndk-bundle/sysroot  -Dsmart_cropper_EXPORTS -I../../../../opencv/include -I../../../../src/main/cpp/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/android/support/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem D:/AndroidSDK/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -frtti -fexceptions -lz -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o -MF CMakeFiles\smart_cropper.dir\src\main\cpp\Scanner.cpp.o.d -o CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o -c D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\Scanner.cpp
clang++.exe: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
In file included from D:\android_pro\internet\SmartCropper-master\smartcropperlib\src\main\cpp\Scanner.cpp:4:
In file included from ../../../../src/main/cpp/include\Scanner.h:8:
In file included from ../../../../opencv/include\opencv2/opencv.hpp:47:
In file included from ../../../../opencv/include\opencv2/core/core.hpp:4883:
../../../../opencv/include\opencv2/core/operations.hpp:74:16: fatal error: 'ext/atomicity.h' file not found
      #include <ext/atomicity.h>
               ^~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by pqpo** [comment]
编译环境问题，你看看：
https://stackoverflow.com/questions/13037659/opencv-build-issue-cant-find-ext-atomicity-h/13037661#13037661
https://stackoverflow.com/questions/50517883/fatal-error-ext-atomicity-h-file-not-found-using-opencv-2-4-11/50546711

**Comment by pqpo** [comment]
编译选项添加 ： arguments '-DANDROID_STL=gnustl_shared'
cmake {
                cppFlags "-std=c++11 -frtti -lz"
                abiFilters 'armeabi-v7a', 'x86'
                arguments '-DANDROID_STL=gnustl_shared'
            }
