### ISSUE TITLE
麻烦大神帮忙看一下，出的这个问题，我真的完全看不懂，也不知道怎么问。。。麻烦您了

### ISSUE THREAD

**Issue by Likeyong** [pqpo/SmartCropper#43]
Build command failed.
Error while executing process /opt/android-sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/codersun/wellsignAS/smartcropperlib/.externalNativeBuild/cmake/debug/x86 --target smart_cropper}
[1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
[2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
[3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
[4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so
FAILED: : && /home/codersun/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=i686-none-linux-android --gcc-toolchain=/home/codersun/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 --sysroot=/home/codersun/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem /home/codersun/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -frtti -fexceptions -lz -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /home/codersun/Android/Sdk/ndk-bundle/platforms/android-14/arch-x86 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/home/codersun/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libsmart_cropper.so -o ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o  ../../../../opencv/lib/x86/libopencv_imgproc.a ../../../../opencv/lib/x86/libopencv_core.a ../../../../opencv/lib/x86/libtbb.a /home/codersun/Android/Sdk/ndk-bundle/platforms/android-14/arch-x86/usr/lib/liblog.so /home/codersun/Android/Sdk/ndk-bundle/platforms/android-14/arch-x86/usr/lib/libjnigraphics.so -latomic -lm "/home/codersun/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libc++_static.a" "/home/codersun/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libc++abi.a" "/home/codersun/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libandroid_support.a" && :
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::Init()'
../../../../opencv/lib/x86/libopencv_imgproc.a(imgwarp.cpp.o):/home/reports/.ccache/tmp/imgwarp.tmp.tegra-server.21155.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::~Init()'
../../../../opencv/lib/x86/libopencv_imgproc.a(smooth.cpp.o):/home/reports/.ccache/tmp/smooth.tmp.tegra-server.21209.ii:function std::vector<double, std::allocator<double> >::_M_fill_insert(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, unsigned int, double const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../opencv/lib/x86/libopencv_imgproc.a(smooth.cpp.o):/home/reports/.ccache/tmp/smooth.tmp.tegra-server.21209.ii:function std::vector<int, std::allocator<int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, unsigned int, int const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../opencv/lib/x86/libopencv_imgproc.a(smooth.cpp.o):/home/reports/.ccache/tmp/smooth.tmp.tegra-server.21209.ii:function std::vector<float, std::allocator<float> >::_M_fill_insert(__gnu_cxx::__normal_iterator<float*, std::vector<float, std::allocator<float> > >, unsigned int, float const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../opencv/lib/x86/libopencv_imgproc.a(contours.cpp.o):/home/reports/.ccache/tmp/contours.tmp.tegra-server.21229.ii:function std::vector<CvSeqBlock, std::allocator<CvSeqBlock> >::_M_fill_insert(__gnu_cxx::__normal_iterator<CvSeqBlock*, std::vector<CvSeqBlock, std::allocator<CvSeqBlock> > >, unsigned int, CvSeqBlock const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../opencv/lib/x86/libopencv_imgproc.a(color.cpp.o):/home/reports/.ccache/tmp/color.tmp.tegra-server.21392.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::Init()'
../../../../opencv/lib/x86/libopencv_imgproc.a(color.cpp.o):/home/reports/.ccache/tmp/color.tmp.tegra-server.21392.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::~Init()'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::Exception::Exception(int, std::string const&, std::string const&, std::string const&, int): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::Exception::formatMessage(): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::Exception::formatMessage(): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::getBuildInformation(): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::assign(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::_M_leak_hard()'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::append(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::append(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::assign(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::append(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(system.cpp.o):/home/reports/.ccache/tmp/system.tmp.tegra-server.14466.ii:function cv::tempfile(char const*): error: undefined reference to 'std::string::append(char const*, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function cv::toUtf16(std::string const&): error: undefined reference to 'std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function cv::toUtf16(std::string const&): error: undefined reference to 'std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(wchar_t const*, std::allocator<wchar_t> const&)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function icvClose(CvFileStorage*, std::string*): error: undefined reference to 'std::string::_M_mutate(unsigned int, unsigned int, unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function icvClose(CvFileStorage*, std::string*): error: undefined reference to 'std::string::resize(unsigned int, char)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function icvClose(CvFileStorage*, std::string*): error: undefined reference to 'std::string::_M_leak_hard()'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function cv::FileStorage::releaseAndGetString(): error: undefined reference to 'std::string::reserve(unsigned int)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function cv::operator<<(cv::FileStorage&, std::string const&): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(persistence.cpp.o):/home/reports/.ccache/tmp/persistenc.tmp.tegra-server.20920.ii:function cv::operator<<(cv::FileStorage&, std::string const&): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::cerr'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::ostream::operator<<(int)'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function cv::gpu::error(char const*, char const*, int, char const*): error: undefined reference to 'std::ostream::flush()'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::Init()'
../../../../opencv/lib/x86/libopencv_core.a(gpumat.cpp.o):/home/reports/.ccache/tmp/gpumat.tmp.tegra-server.21044.ii:function global constructors keyed to a: error: undefined reference to 'std::ios_base::Init::~Init()'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::handle_perror(int, char const*): error: undefined reference to 'std::runtime_error::runtime_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::invalid_argument::invalid_argument(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::out_of_range::out_of_range(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::range_error::range_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::range_error::range_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::runtime_error::runtime_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::runtime_error::runtime_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::runtime_error::runtime_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::out_of_range::out_of_range(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::out_of_range::out_of_range(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::invalid_argument::invalid_argument(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::length_error::length_error(std::string const&)'
../../../../opencv/lib/x86/libtbb.a(tbb_misc.cpp.o):/home/reports/.ccache/tmp/tbb_misc.tmp.tegra-server.14427.ii:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::out_of_range::out_of_range(std::string const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by pqpo** [comment]
只编译 armeabi 试试， 把其他的先注释掉。
