### ISSUE TITLE
How to set point on image's corner

### ISSUE THREAD

**Issue by Dhaval11296** [pqpo/SmartCropper#44]
Whew i click photo from camera & pick image from gallery then all point set to four corner, not image between or other image area,

Like want :=>
![screenshot_2018-08-27-14-10-16-820_com digiwallet](https://user-images.githubusercontent.com/16969916/44650025-2ceaa880-aa03-11e8-8a9d-5c50c5617ba5.png)

Not Like :=>
![screenshot_2018-08-27-14-10-01-318_com digiwallet](https://user-images.githubusercontent.com/16969916/44650043-38d66a80-aa03-11e8-9652-af91f13ae67d.png)

Please help, Thanks.

**Comment by pqpo** [comment]
You can call setFullImgCrop();

**Comment by Dhaval11296** [comment]
Okay, Thanks
