### ISSUE TITLE
编译TBB报错

### ISSUE THREAD

**Issue by limin05030** [pqpo/SmartCropper#5]
你好，我用你的代码在编译的时候报TBB错，这个该怎么解决呐？

错误信息如下：
`Error while executing process E:\sens\android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build G:\android\projects\demo\SmartCropper\smartcropperlib\.externalNativeBuild\cmake\release\armeabi-v7a --target smart_cropper}
[1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\release\obj\armeabi-v7a\libsmart_cropper.so
FAILED: cmd.exe /C "cd . && E:\sens\android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=E:/sens/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=E:/sens/android/sdk/ndk-bundle/sysroot -fPIC -isystem E:/sens/android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -lz -Os -DNDEBUG  -Wl,--exclude-libs,libgcc.a --sysroot E:/sens/android/sdk/ndk-bundle/platforms/android-16/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libsmart_cropper.so -o ..\..\..\..\build\intermediates\cmake\release\obj\armeabi-v7a\libsmart_cropper.so CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o  ../../../../opencv/lib/armeabi-v7a/libopencv_imgproc.a ../../../../opencv/lib/armeabi-v7a/libopencv_core.a -llog -ljnigraphics -lm "E:/sens/android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a" && cd ."
../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::~start_for(): error: undefined reference to 'vtable for tbb::task'
  E:/sens/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::flag_task::~flag_task(): error: undefined reference to 'vtable for tbb::task'
  E:/sens/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::task_scheduler_init::~task_scheduler_init(): error: undefined reference to 'tbb::task_scheduler_init::terminate()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::flag_task::~flag_task(): error: undefined reference to 'vtable for tbb::task'
  E:/sens/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::~start_for(): error: undefined reference to 'vtable for tbb::task'
  E:/sens/android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::task_group_context::init()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::internal::allocate_root_with_context_proxy::allocate(unsigned int) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::internal::get_initial_auto_partitioner_divisor()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::task_group_context::~task_group_context()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::task_group_context::~task_group_context()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double): error: undefined reference to 'tbb::internal::allocate_root_with_context_proxy::free(tbb::task&) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::getNumThreads(): error: undefined reference to 'tbb::task_scheduler_init::default_num_threads()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::setNumThreads(int): error: undefined reference to 'tbb::task_scheduler_init::terminate()'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function cv::setNumThreads(int): error: undefined reference to 'tbb::task_scheduler_init::initialize(int)'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::execute(): error: undefined reference to 'tbb::internal::allocate_continuation_proxy::allocate(unsigned int) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::execute(): error: undefined reference to 'tbb::internal::allocate_child_proxy::allocate(unsigned int) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::execute(): error: undefined reference to 'tbb::task_group_context::is_group_execution_cancelled() const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::execute(): error: undefined reference to 'tbb::internal::allocate_continuation_proxy::allocate(unsigned int) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>::execute(): error: undefined reference to 'tbb::internal::allocate_child_proxy::allocate(unsigned int) const'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:function _GLOBAL__sub_I_parallel.cpp: error: undefined reference to 'tbb::task_scheduler_init::initialize(int, unsigned int)'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:vtable for tbb::interface7::internal::flag_task: error: undefined reference to 'tbb::task::note_affinity(unsigned short)'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:typeinfo for tbb::interface7::internal::flag_task: error: undefined reference to 'typeinfo for tbb::task'
  ../../../../opencv/lib/armeabi-v7a/libopencv_core.a(parallel.cpp.o):parallel.cpp:typeinfo for tbb::interface7::internal::start_for<tbb::blocked_range<int>, (anonymous namespace)::ProxyLoopBody, tbb::auto_partitioner const>: error: undefined reference to 'typeinfo for tbb::task'
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.`

**Comment by pqpo** [comment]
我是在 Linux 下编译的，还没在 Windows 下编译过，我试一下。能配置成不用 TBB 吗？

**Comment by pqpo** [comment]
参考一下这个：https://github.com/pqpo/SmartCropper/issues/6

**Comment by limin05030** [comment]
好的 非常感谢，解决了
