### ISSUE TITLE
裁剪边缘识别还不太好   有时就集中在一起了    

### ISSUE THREAD

**Issue by yangxiansheng123** [pqpo/SmartCropper#52]
后续希望  加一个功能  裁剪后 生成多个对比图片

**Comment by yangxiansheng123** [comment]
![screenshot_20180927-104046](https://user-images.githubusercontent.com/19617325/46120474-71f03d80-c242-11e8-8382-883586bf380e.jpg)  就是这样的问题       裁剪聚集在一起了

**Comment by pqpo** [comment]
这个是因为识别出来的边框恰好是窗户那个位置。

**Comment by pqpo** [comment]
暂时先关闭了，有其他问题再重新回复打开。
