### ISSUE TITLE
 java.lang.UnsatisfiedLinkError [support for arm64-v8a]

### ISSUE THREAD

**Issue by Marchuck** [pqpo/SmartCropper#53]
Hello there! First of all, thanks for amazing library, it works perfect for cropping documents! 
I faced a few crashes in my app, and I figured out on particular devices with architecture arm64-v8a
this could not work (.so for this platform is missing - only armeabi-v7a,armeabi,mips,x86 for now)
https://github.com/pqpo/SmartCropper/tree/master/libs

https://handstandsam.com/2016/01/28/determining-supported-processor-types-abis-for-an-android-device/

Do you know how to support this architecture? Or some guide / tutorial, so I can make pull request with the support

BR

Lukasz

**Comment by pqpo** [comment]
Thank you for your feedback! 
The OpenCV android SDK only provided armeabi-v7a, armeabi, mips, x86, I also have no idea to compile it.
![image](https://user-images.githubusercontent.com/7626969/46140596-1d6db200-c284-11e8-8a6b-0275c442fb61.png)
You can try to remove all the architecture folders except the armeabi, so all architecture divices will use armeabi.
If you have a better way, you can tell me please.

**Comment by lukasz-marczak-contractor** [comment]
Thanks, for now I have one particular case where it fails. To prevent crashes, I have some workaround:

```
 private void loadUriOntoImage(Uri selectedUri) {
        
        Bitmap bitmap = resolveBitmapFromUri(selectedUri);
        if (bitmap != null) {
            try {
                ivCrop.setImageToCrop(bitmap);
            } catch (UnsatisfiedLinkError error) {
                showToastLong(getString(R.string.device_not_supports_this_feature));
            }
        } 
    }
```

`UnsatisfiedLinkError` inhertis from `Error` and it is not advised to catch these kinds of throwables, but I am doing this only to prevent crashes.

**Comment by Marchuck** [comment]
Thanks, for now I have one particular case where it fails. To prevent crashes, I have some workaround:
```
 private void loadUriOntoImage(Uri selectedUri) {
        
        Bitmap bitmap = resolveBitmapFromUri(selectedUri);
        if (bitmap != null) {
            try {
                ivCrop.setImageToCrop(bitmap);
            } catch (UnsatisfiedLinkError error) {
                showToastLong(getString(R.string.device_not_supports_this_feature));
            }
        } 
    }
```
`UnsatisfiedLinkError` inhertis from `Error` and it is not advised to catch these kinds of throwables, but I am doing this only to prevent crashes.

**Comment by z4hyoung** [comment]
Hi, 

OpenCV-android-sdk v3.4.3 has provided arm64-v8a static libs, as many devices already support this ABI, can you help to upgrade this library please? Thanks.

**Comment by pqpo** [comment]
I will try to support for arm64-v8a !

**Comment by BCsl** [comment]
Specifying abi may solve this problem temporarily
` ndk {
      abiFilters 'armeabi-v7a', 'x86'
}`

**Comment by z4hyoung** [comment]
Hi @pqpo 

Could you help to support arm64-v8a please? I tried to add those static lib and failed, it seems some API of OpenCV changed between v3.4.3 and current one. The other libs in my project are arm64-v8a, I can not run my app if include this lib :(
