### ISSUE TITLE
Expected NDK STL shared object file at /home/smart/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_shared.so

### ISSUE THREAD

**Issue by Slake07** [pqpo/SmartCropper#55]
I tried to run given example facing this error.

Expected NDK STL shared object file at /home/ss/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_shared.so

I dont know what is the reason for that.

**Comment by pqpo** [comment]
try to delete this line ``` arguments '-DANDROID_STL=gnustl_shared' ``` in the file :https://github.com/pqpo/SmartCropper/blob/master/smartcropperlib/build.gradle

**Comment by hongtou820** [comment]
我删除后得到这样问题
Execution failed for task ':smartcropperlib:externalNativeBuildDebug'.

../../../../opencv/include\opencv2/core/operations.hpp:74:16: fatal error: 'ext/atomicity.h' file not found
      #include <ext/atomicity.h>


https://github.com/pqpo/SmartCropper/issues/55#issuecomment-429730414

**Comment by z4hyoung** [comment]
Try to downgrade NDK version to R17C.

**Comment by zhengjingfeng** [comment]
?

**Comment by zhengjingfeng** [comment]
问题解决了没有

**Comment by pqpo** [comment]
Try to downgrade NDK version to R17C.

**Comment by kobeumut** [comment]
I downgraded ndk version to R17C but i get still error
`Execution failed for task ':smartcropperlib:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/umut/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/umut/Documents/GitHub/SmartCropper/smartcropperlib/.externalNativeBuild/cmake/debug/x86 --target smart_cropper}
  [1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
  clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
  [2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
  clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
  [3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
  clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
  [4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so
  FAILED: ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so `

**Comment by geekqian** [comment]
> I downgraded ndk version to R17C but i get still error
> `Execution failed for task ':smartcropperlib:externalNativeBuildDebug'.
> 
> > Build command failed.
> > Error while executing process /Users/umut/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/umut/Documents/GitHub/SmartCropper/smartcropperlib/.externalNativeBuild/cmake/debug/x86 --target smart_cropper}
> > [1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
> > clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
> > [2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
> > clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
> > [3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
> > clang++: warning: -lz: 'linker' input unused [-Wunused-command-line-argument]
> > [4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so
> > FAILED: ../../../../build/intermediates/cmake/debug/obj/x86/libsmart_cropper.so `

ndk version R17C and change this line `arguments '-DANDROID_STL=gnustl_shared'`  to  `arguments '-DANDROID_STL=gnustl_static'`

**Comment by walkmn** [comment]
CMake Error at /Users/user/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:249 (message):
  gnustl_static is no longer supported.  Please switch to either c++_shared
  or c++_static.

**Comment by geekqian** [comment]
> CMake Error at /Users/user/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:249 (message):
> gnustl_static is no longer supported. Please switch to either c++_shared
> or c++_static.

Just a warn. Ignore this prompt and check other errors.

**Comment by lokeshdesai403** [comment]
@geekqian Have you got a solution for this error?
