### ISSUE TITLE
多边形问题

### ISSUE THREAD

**Issue by xiaojiebudai** [pqpo/SmartCropper#56]
实际使用过程，材料折角了，变成了五边形，有好的处理方案么？

**Comment by pqpo** [comment]
贴个图呗

**Comment by xiaojiebudai** [comment]
![screenshot_20181012-173428](https://user-images.githubusercontent.com/15228504/46879145-cff26700-ce77-11e8-941f-4c166da4d54b.jpg)
![screenshot_20181012-173451](https://user-images.githubusercontent.com/15228504/46879213-fd3f1500-ce77-11e8-8d27-97c0ee8e134d.jpg)

**Comment by xiaojiebudai** [comment]
> 贴个图呗

就是图上那样的，有的材料缺了个角，或者拍照的时候缺角了，会造成纸张内内容部分被裁掉了，有没有多边形去黑边的方法

**Comment by pqpo** [comment]
这种情况目前只能用户手动调节了。
或者要调整识别算法，比如寻找四边交点，实现复杂度提高了许多

**Comment by killpoer3** [comment]
![device-2018-11-06-180131](https://user-images.githubusercontent.com/8450250/48057056-12e0f980-e1ee-11e8-8cef-6b1429d34b0f.png)
边框识别不行

**Comment by pqpo** [comment]
受环境及背景影响，不是百分百识别成功的
