### ISSUE TITLE
Failed to resolve: com.github.pqpo:SmartCropper:v1.2.4 Show in File Show in Project Structure dialog

### ISSUE THREAD

**Issue by BaiXiaoYan** [pqpo/SmartCropper#62]
Please check this error.

**Comment by pqpo** [comment]
Try to use v1.2.3 or clone and compile locally. If cannot compiled successfully, try to downgrade NDK version to R17C.

**Comment by BaiXiaoYan** [comment]
Why can't use 1.2.4 version?

**Comment by pqpo** [comment]
It compiled by Jitpack, The version of NDK is newer than R17C.
