### ISSUE TITLE
ERROR: Failed to resolve: com.github.pqpo:SmartCropper:v1.2.4

### ISSUE THREAD

**Issue by yundequanshi** [pqpo/SmartCropper#63]
ERROR: Failed to resolve: com.github.pqpo:SmartCropper:v1.2.4
Show in Project Structure dialog
Affected Modules: app

怎么解决呀

**Comment by petrezhao** [comment]
@pqpo  can you reply please?

**Comment by pqpo** [comment]
先使用 1.2.3

**Comment by hafiz013** [comment]
You have download manually file 1.2.5 instead of using gradle
