### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libgnustl_shared.so'

### ISSUE THREAD

**Issue by hVenus** [pqpo/SmartCropper#65]
引用的1.2.3版。
编译报这个错误。

要怎么解决？

**Comment by AshuTyagi16** [comment]
Add this to your build.gradle:

   packagingOptions {
        pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
        pickFirst 'lib/x86/libgnustl_shared.so'
    }

**Comment by hVenus** [comment]
@AshuTyagi16 没有任何用处啊！
