### ISSUE TITLE
去掉中心点报错

### ISSUE THREAD

**Issue by xiaojintongxue** [pqpo/SmartCropper#69]
布局加入   app:civShowEdgeMidPoint="false"属性
异常崩溃
 java.lang.NullPointerException: Attempt to get length of null array

**Comment by xiaojintongxue** [comment]
解决方案  CropImageView 617行添加判断校验
 //边锚点
        if (mShowEdgeMidPoint) {
            for (Point point : mEdgeMidPoints) {
                canvas.drawCircle(getViewPointX(point), getViewPointY(point), dp2px(POINT_RADIUS), mPointFillPaint);
                canvas.drawCircle(getViewPointX(point), getViewPointY(point), dp2px(POINT_RADIUS), mPointPaint);
            }
        }

**Comment by xiaojintongxue** [comment]
CropImageView  617行添加   //边锚点
        if (!mShowEdgeMidPoint) {
            return;
        }
657行添加  

if(!mShowEdgeMidPoint){
            return null;
        }
        for (Point p : mEdgeMidPoints) {
            if (isTouchPoint(p, event)) return p;
        }

**Comment by pqpo** [comment]
可以提个 pr

**Comment by xiaojintongxue** [comment]
已fork提交

**Comment by pqpo** [comment]
可以给我提个 pr 我 merge 一下
