### ISSUE TITLE
大佬可以把旋转也加上去吗，还有识别有一定几率会反向

### ISSUE THREAD

**Issue by weather2rain** [pqpo/SmartCropper#73]
裁剪之后，得到的图片，有大概五十分之一二左右图片会变向

**Comment by gongchaobin** [comment]
public void rotate(int degrees) {
        Bitmap bitmap = getBitmap();
        if (bitmap == null) {
            return;
        }
        Matrix matrix = new Matrix();

        int dx = bitmap.getWidth() / 2;
        int dy = bitmap.getHeight() / 2;

        matrix.postTranslate(-dx, -dy);
        matrix.postRotate(degrees);
        matrix.postTranslate(dy, dx);
        Bitmap scaledBitmap = bitmap;
        Bitmap rotatedBitmap = Bitmap.createBitmap(scaledBitmap.getHeight(), scaledBitmap.getWidth(),
                Bitmap.Config.RGB_565);
        Canvas canvas = new Canvas(rotatedBitmap);
        canvas.drawBitmap(bitmap, matrix, null);
        bitmap.recycle();
        bitmap = rotatedBitmap;
        setImageToCrop(bitmap);
        invalidate();
    }
可以试试这样子

**Comment by gongchaobin** [comment]
` public void rotate(int degrees) {
        Bitmap bitmap = getBitmap();
        if (bitmap == null) {
            return;
        }
        Matrix matrix = new Matrix();

        int dx = bitmap.getWidth() / 2;
        int dy = bitmap.getHeight() / 2;

        matrix.postTranslate(-dx, -dy);
        matrix.postRotate(degrees);
        matrix.postTranslate(dy, dx);
        Bitmap scaledBitmap = bitmap;
        Bitmap rotatedBitmap = Bitmap.createBitmap(scaledBitmap.getHeight(), scaledBitmap.getWidth(),
                Bitmap.Config.RGB_565);
        Canvas canvas = new Canvas(rotatedBitmap);
        canvas.drawBitmap(bitmap, matrix, null);
        bitmap.recycle();
        bitmap = rotatedBitmap;
        setImageToCrop(bitmap);
        invalidate();
    }
`
直接用这个试试

**Comment by gongchaobin** [comment]
如下： 
`
 public void rotate(int degrees) {
        Bitmap bitmap = getBitmap();
        if (bitmap == null) {
            return;
        }
        Matrix matrix = new Matrix();

        int dx = bitmap.getWidth() / 2;
        int dy = bitmap.getHeight() / 2;

        matrix.postTranslate(-dx, -dy);
        matrix.postRotate(degrees);
        matrix.postTranslate(dy, dx);
        Bitmap scaledBitmap = bitmap;
        Bitmap rotatedBitmap = Bitmap.createBitmap(scaledBitmap.getHeight(), scaledBitmap.getWidth(),
                Bitmap.Config.RGB_565);
        Canvas canvas = new Canvas(rotatedBitmap);
        canvas.drawBitmap(bitmap, matrix, null);
        bitmap.recycle();
        bitmap = rotatedBitmap;
        setImageToCrop(bitmap);
        invalidate();
    }

`
