### ISSUE TITLE
SmartCropper need support 'arm64-v8a' and 'x86_64'

### ISSUE THREAD

**Issue by hafiz013** [pqpo/SmartCropper#74]
To comply with google policy, the apps should be able to support 64 architecture . So please update u library that support those 64-bit architecture. I suspect this library only support x86 and armeabi-v7a

**Comment by hafiz013** [comment]
![Uploading Screenshot 2019-05-23 at 3.14.43 PM.png…](those two library need to support 64 bit)

**Comment by pqpo** [comment]
This three architectures is supported: armeabi-v7a、arm64-v8a、x86

**Comment by hafiz013** [comment]
Ok u have to download manually aar file 1.2.5 instead of gradle. Why?

**Comment by hoanganhtuan95ptit** [comment]
Answer here https://github.com/pqpo/SmartCropper/issues/62

**Comment by harisribic** [comment]
@pqpo Would it be possible to compile the library for **x86_64** architecture as well?

Google Play requires it from 1. August onwards

**Comment by DomenCai** [comment]
同求，8月1号上家google play的应用就要支持64位，昨天发包上去后有这个警告
![image](https://user-images.githubusercontent.com/13468242/58686347-300b2e80-83b1-11e9-8bf7-e6f291c9efb4.png)

**Comment by pqpo** [comment]
@harisribic Now it's supported arm64-v8a,  Google request must support both arm64-v8a and x86_64?

**Comment by harisribic** [comment]
@pqpo Yes, it is explicitly stated that **armeabi-v7a**, **arm64-v8a**, **x86** and **x86_64** need to be supported.

https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by hafiz013** [comment]
Please conduct in English so that everyone can understand the issue. Please

**Comment by YugengWang** [comment]
We need to support x86_64 too,if you want to compile the library for x86_64?

**Comment by harisribic** [comment]
@pqpo Could you compile the library for x86_64 as well? Otherwise I would need to find another library, since apps will no longer be supported...

**Comment by pqpo** [comment]
The OpenCV library with the version of v2.4.11  is not provided  the shared libraries for x86_64 , and I have try to update the OpenCV lib, but it seem to be incompatibility of API. Can anybody provide 
 the OpenCV shared libraries  for x86_64 with the version of v2.4.11?  Thanks a lot!

**Comment by Tomhouxin** [comment]
替换opencv版本之后，smartcropperlib一直编译不过呢，想用opencv3的版本，armeabi

**Comment by pqpo** [comment]
@Tomhouxin 新的 OpenCV 版本可能有 api 改动

**Comment by Tomhouxin** [comment]
那只能用旧版本了？
