### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by chengkaizone** [pqpo/SmartCropper#77]
Compile error
../../../../opencv/include/opencv2/core/operations.hpp:74:16: fatal error: 'ext/atomicity.h' file not found
<img width="1437" alt="截图" src="https://user-images.githubusercontent.com/6120008/60242756-0af2d880-98e9-11e9-9b62-70245fce4e26.png">

**Comment by pqpo** [comment]
upgrade to v2.1.1
