### ISSUE TITLE
v1.2.3 版本无法下载，打包失败

### ISSUE THREAD

**Issue by violinday** [pqpo/SmartCropper#78]
希望可以重新上传 v1.2.3 版本的 aar 到 jitpack.

**Comment by pqpo** [comment]
推荐使用最新的 v2.1.1 版本，
1. Jitpack 打包使用的是最新的 NDK 版本，v1.2.3及以下版本只能使用较低版本的 NDK 编译。
2. 一定要使用 v1.2.3 及以下版本，在 release 页面自行下载 aar 包导入。
