### ISSUE TITLE
浅色背景 黑色的物体，识别率低

### ISSUE THREAD

**Issue by yndongyong** [pqpo/SmartCropper#8]
对于浅色背景 黑色的物体（手机等）容易反光的，识别区域成了放光的区域

**Comment by pqpo** [comment]
这种方式确实有局限性，比较理想的是使用卷积网络结合 OpenCV，参考 http://fengjian0106.github.io/2017/05/08/Document-Scanning-With-TensorFlow-And-OpenCV/
