### ISSUE TITLE
 SmartCropper.buildImageDetector(context);速度慢

### ISSUE THREAD

**Issue by lianmingran** [pqpo/SmartCropper#82]
感觉使用  SmartCropper.buildImageDetector(context);速度变慢了，一些图片的识别反而没有原来识别的好

**Comment by pqpo** [comment]
嗯，这个还是实验阶段，如果效果不好可以不加 SmartCropper.buildImageDetector(context); 这样会使用原来的 Canny 算法。后续可以自己训练模型。
