### ISSUE TITLE
我在编译的时候遇到问题  minSdkVersion比21小时，导致编译错误。

### ISSUE THREAD

**Issue by TianHeZheng** [pqpo/SmartCropper#88]
![image](https://user-images.githubusercontent.com/35953595/63592021-1c9fe600-c5e3-11e9-84ef-ebeeb05ddcea.png)
截图如下 ，请问是这是如何导致的

**Comment by pqpo** [comment]
是的，新版本 OpenCV minSdkVersion 必须大于等于 21
