### ISSUE TITLE
couldn't find "libsmart_cropper.so"

### ISSUE THREAD

**Issue by lennonliuyong** [pqpo/SmartCropper#9]
我在根目录添加了libs-->armeabi--->libsmart_cropper.so

**Comment by pqpo** [comment]
不手动添加，使用 compile ‘com.github.pqpo:SmartCropper:V1.0.1@aar’ 试试看可以吗？

**Comment by lennonliuyong** [comment]
Hi 还是不行

**Comment by lennonliuyong** [comment]
我是按照 接入说明 build.gradle 实现的 7.0系统

**Comment by pqpo** [comment]
我刚试了一下是可以的，clean 一下工程试试

**Comment by lennonliuyong** [comment]
我在app的build.gradle中 添加了 ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a','x86', 'x86_64', 'mips', 'mips64'} 这样会有影响吗

**Comment by lennonliuyong** [comment]
ivCrop.setImageToCrop(selectedBitmap);这一行报错 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList。。。。。。。。couldn't find "libsmart_cropper.so"

**Comment by pqpo** [comment]
现在提供的编译包里只有 armeabi ，其他平台的可以集成源代码自行编译看看

**Comment by lennonliuyong** [comment]
可以进行选择区域内锐化吗 类似全能扫描王那样

**Comment by pqpo** [comment]
可以的，OpenCV 支持很多图像处理功能。现在能正常编译了吗？
