### ISSUE TITLE
Dataset and training code for HED model

### ISSUE THREAD

**Issue by ofirkris** [pqpo/SmartCropper#92]
Hello, thanks for sharing this project.
Where can I find Dataset and training code for HED model?

**Comment by pqpo** [comment]
Training code：https://github.com/pqpo/SmartCropper/tree/master/edge_detection
In fact, you can fine tuning by trained HED model, and the dataset you can find from this project: https://github.com/fengjian0106/hed-tutorial-for-document-scanning.
