### ISSUE TITLE
 undefined reference to 'fesetenv'

### ISSUE THREAD

**Issue by Mangosir** [pqpo/SmartCropper#93]
我新建一个工程，把lib拷贝到module里，但是编译报错
`/build/master_pack-android/build/o4a/3rdparty/tbb/tbb-2018_U1/src/tbb/scheduler_common.h:435: error: undefined reference to 'fesetenv'`

不知道啥情况

**Comment by LoggerWang** [comment]
同上

**Comment by skyscrapy** [comment]
Make sure that version of com.android.tools.build is identical to his lib and it should work well.

**Comment by yuround** [comment]
解决了吗，我也报错┭┮﹏┭┮

**Comment by wcq19941215** [comment]
@yuround 遇到这个问题，一般是修改了 作者原本提供的这个依赖com.android.tools.build:gradle:3.2.1
千万别根据AS的提示升级，特别是AS最新版本。具体解决方案如下：
1、在AS最新版本中，因为自带支持的java11，需要将Gradle Version 设置为5.0或者以上，在Project Structure中可以设置
2、此时build.gradle中的minSdkVersion会变成19（此时 com.android.tools.build:gradle:3.2.1 不要变！！！！）
简单来说，就是不要根据AS的提示，修改com.android.tools.build:gradle:3.2.1！！
