### ISSUE TITLE
clone工程直接导入AndroidStudio

### ISSUE THREAD

**Issue by leiiiooo** [pqpo/SmartCropper#96]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smartcropperlib:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/leyliang/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/leyliang/Desktop/SmartCropper/smartcropperlib/.externalNativeBuild/cmake/debug/arm64-v8a --target smart_cropper}
  [1/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/smart_cropper.cpp.o
  [2/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/android_utils.cpp.o
  [3/4] Building CXX object CMakeFiles/smart_cropper.dir/src/main/cpp/Scanner.cpp.o
  [4/4] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libsmart_cropper.so
  FAILED: : && /Users/leyliang/Library/Android/sdk/ndk/16.1.4479499/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=aarch64-none-linux-android --gcc-toolchain=/Users/leyliang/Library/Android/sdk/ndk/16.1.4479499/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/leyliang/Library/Android/sdk/ndk/16.1.4479499/sysroot -fPIC -isystem /Users/leyliang/Library/Android/sdk/ndk/16.1.4479499/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /Users/leyliang/Library/Android/sdk/ndk/16.1.4479499/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libsmart_cropper.so -
...
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
`

**Comment by Cazaea** [comment]
大佬, 问题解决了吗?

**Comment by Cazaea** [comment]
同样问题, 求解...
